PROFILE_STARTUP=false
if [[ "$PROFILE_STARTUP" == true ]]; then
    # http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
    PS4=$'%D{%M%S%.} %N:%i> '
    exec 3>&2 2>$HOME/tmp/startlog.$$
    setopt xtrace prompt_subst
fi

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache


export DOTFILEDIR="$(cat $HOME/.dotfilepath)"
source "$DOTFILEDIR/functions/common.sh"

# antigen for zsh
source "$DOTFILEDIR/zsh/antigenplugins.zsh"

#paths
source "$DOTFILEDIR/paths/$(platform_get).paths"

#aliases
source "$DOTFILEDIR/alias/common.alias"
source "$DOTFILEDIR/alias/$(platform_get).alias"

source "$HOME/.dotfile_local/zshrc.local" 2>/dev/null

# Colorize a bunch of stuff
source "`brew --prefix`/etc/grc.bashrc"

#vi mode
set -o vi

# why would you type 'cd dir' if you could just type 'dir'?
 setopt AUTO_CD
#
 unsetopt CASE_GLOB

# # 10 second wait if you do something that will delete everything.  I wish I'd had this before...
 setopt RM_STAR_WAIT
#
 setopt NO_HUP
#
 export EDITOR="nvim"
#
# # Keep echo "station" > station from clobbering station
 setopt NO_CLOBBER
#
# # Case insensitive globbing
 setopt NO_CASE_GLOB
#
# # Be Reasonable!
 setopt NUMERIC_GLOB_SORT
#
# # I don't know why I never set this before.
 setopt EXTENDED_GLOB
#
# # Who doesn't want home and end to work?
 bindkey '\e[1~' beginning-of-line
 bindkey '\e[4~' end-of-line

# # Incremental search is elite!
 #bindkey -M vicmd "j" up-line-or-beginning-search # Up
 #bindkey -M vicmd "k" down-line-or-beginning-search # Down

 bindkey -M vicmd "/" history-incremental-search-backward
 bindkey -M vicmd "?" history-incremental-search-forward
#
# # Search based on what you typed in already
 bindkey -M vicmd "j" history-beginning-search-backward
 bindkey -M vicmd "k" history-beginning-search-forward
#
# bindkey "\eOP" run-help
#
# # oh wow!  This is killer...  try it!
 bindkey -M vicmd "q" push-line
#
# # it's like, space AND completion.  Gnarlbot.
 bindkey -M viins ' ' magic-space
 bindkey -M viins 'jj' vi-cmd-mode
#
# Compact completion
setopt listpacked

# Verify hist commands
setopt histverify
# Zsh Line editor - on by default
setopt ZLE

unsetopt incappendhistory


if [[ "$PROFILE_STARTUP" == true ]]; then
    unsetopt xtrace
    exec 2>&3 3>&-
fi

